### ISSUE TITLE
PHPStorm 10 support

### ISSUE THREAD

**Issue by OzzyCzech** [nicity/CppTools#20] opened 2015-11-03 14:15 UTC
It's possible add PHPStorm 10 support?

**Comment by jrabbe** [comment] 2015-11-03 15:38
Related, it seems the newest version from https://plugins.jetbrains.com/plugin/1373 is not compatible with WebStorm 11 either.

**Comment by nicity** [comment] 2015-11-03 22:50
Dupe of #19

**Closed** 2015-11-03 22:49 UTC
