### ISSUE TITLE
Incompatible with Pycharm 5.0.1

### ISSUE THREAD

**Issue by Symmetric** [nicity/CppTools#23] opened 2015-12-04 00:56 UTC
According to the [Jetbrains plugin page](https://plugins.jetbrains.com/plugin/1373?pr=pycharm), this plugin is compatible with Pycharm. However, it's not listed in the in-app plugin list in 5.0.1, and attempting to manually load 0.8 Build {5..8} from file fails.

**Comment by nicity** [comment] 2015-12-04 09:51
Duplicate of #19

**Closed by nicity** 2015-12-04 09:51 UTC
